/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSongsRouteImport } from './routes/app/songs'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppPlaylistsIndexRouteImport } from './routes/app/playlists/index'
import { Route as AppGenresIndexRouteImport } from './routes/app/genres/index'
import { Route as AppArtistsIndexRouteImport } from './routes/app/artists/index'
import { Route as AppAlbumsIndexRouteImport } from './routes/app/albums/index'
import { Route as AppPlaylistsIdRouteImport } from './routes/app/playlists/$id'
import { Route as AppGenresGenreRouteImport } from './routes/app/genres/$genre'
import { Route as AppArtistsIdRouteImport } from './routes/app/artists/$id'
import { Route as AppAlbumsIdRouteImport } from './routes/app/albums/$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSongsRoute = AppSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaylistsIndexRoute = AppPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenresIndexRoute = AppGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArtistsIndexRoute = AppArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsIndexRoute = AppAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaylistsIdRoute = AppPlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenresGenreRoute = AppGenresGenreRouteImport.update({
  id: '/genres/$genre',
  path: '/genres/$genre',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArtistsIdRoute = AppArtistsIdRouteImport.update({
  id: '/artists/$id',
  path: '/artists/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsIdRoute = AppAlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/songs': typeof AppSongsRoute
  '/app/': typeof AppIndexRoute
  '/app/albums/$id': typeof AppAlbumsIdRoute
  '/app/artists/$id': typeof AppArtistsIdRoute
  '/app/genres/$genre': typeof AppGenresGenreRoute
  '/app/playlists/$id': typeof AppPlaylistsIdRoute
  '/app/albums/': typeof AppAlbumsIndexRoute
  '/app/artists/': typeof AppArtistsIndexRoute
  '/app/genres/': typeof AppGenresIndexRoute
  '/app/playlists/': typeof AppPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/songs': typeof AppSongsRoute
  '/app': typeof AppIndexRoute
  '/app/albums/$id': typeof AppAlbumsIdRoute
  '/app/artists/$id': typeof AppArtistsIdRoute
  '/app/genres/$genre': typeof AppGenresGenreRoute
  '/app/playlists/$id': typeof AppPlaylistsIdRoute
  '/app/albums': typeof AppAlbumsIndexRoute
  '/app/artists': typeof AppArtistsIndexRoute
  '/app/genres': typeof AppGenresIndexRoute
  '/app/playlists': typeof AppPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/songs': typeof AppSongsRoute
  '/app/': typeof AppIndexRoute
  '/app/albums/$id': typeof AppAlbumsIdRoute
  '/app/artists/$id': typeof AppArtistsIdRoute
  '/app/genres/$genre': typeof AppGenresGenreRoute
  '/app/playlists/$id': typeof AppPlaylistsIdRoute
  '/app/albums/': typeof AppAlbumsIndexRoute
  '/app/artists/': typeof AppArtistsIndexRoute
  '/app/genres/': typeof AppGenresIndexRoute
  '/app/playlists/': typeof AppPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/songs'
    | '/app/'
    | '/app/albums/$id'
    | '/app/artists/$id'
    | '/app/genres/$genre'
    | '/app/playlists/$id'
    | '/app/albums/'
    | '/app/artists/'
    | '/app/genres/'
    | '/app/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/settings'
    | '/app/songs'
    | '/app'
    | '/app/albums/$id'
    | '/app/artists/$id'
    | '/app/genres/$genre'
    | '/app/playlists/$id'
    | '/app/albums'
    | '/app/artists'
    | '/app/genres'
    | '/app/playlists'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/songs'
    | '/app/'
    | '/app/albums/$id'
    | '/app/artists/$id'
    | '/app/genres/$genre'
    | '/app/playlists/$id'
    | '/app/albums/'
    | '/app/artists/'
    | '/app/genres/'
    | '/app/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/songs': {
      id: '/app/songs'
      path: '/songs'
      fullPath: '/app/songs'
      preLoaderRoute: typeof AppSongsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playlists/': {
      id: '/app/playlists/'
      path: '/playlists'
      fullPath: '/app/playlists/'
      preLoaderRoute: typeof AppPlaylistsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/genres/': {
      id: '/app/genres/'
      path: '/genres'
      fullPath: '/app/genres/'
      preLoaderRoute: typeof AppGenresIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/artists/': {
      id: '/app/artists/'
      path: '/artists'
      fullPath: '/app/artists/'
      preLoaderRoute: typeof AppArtistsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/albums/': {
      id: '/app/albums/'
      path: '/albums'
      fullPath: '/app/albums/'
      preLoaderRoute: typeof AppAlbumsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playlists/$id': {
      id: '/app/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/app/playlists/$id'
      preLoaderRoute: typeof AppPlaylistsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/genres/$genre': {
      id: '/app/genres/$genre'
      path: '/genres/$genre'
      fullPath: '/app/genres/$genre'
      preLoaderRoute: typeof AppGenresGenreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/artists/$id': {
      id: '/app/artists/$id'
      path: '/artists/$id'
      fullPath: '/app/artists/$id'
      preLoaderRoute: typeof AppArtistsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/albums/$id': {
      id: '/app/albums/$id'
      path: '/albums/$id'
      fullPath: '/app/albums/$id'
      preLoaderRoute: typeof AppAlbumsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppSongsRoute: typeof AppSongsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumsIdRoute: typeof AppAlbumsIdRoute
  AppArtistsIdRoute: typeof AppArtistsIdRoute
  AppGenresGenreRoute: typeof AppGenresGenreRoute
  AppPlaylistsIdRoute: typeof AppPlaylistsIdRoute
  AppAlbumsIndexRoute: typeof AppAlbumsIndexRoute
  AppArtistsIndexRoute: typeof AppArtistsIndexRoute
  AppGenresIndexRoute: typeof AppGenresIndexRoute
  AppPlaylistsIndexRoute: typeof AppPlaylistsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppSongsRoute: AppSongsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumsIdRoute: AppAlbumsIdRoute,
  AppArtistsIdRoute: AppArtistsIdRoute,
  AppGenresGenreRoute: AppGenresGenreRoute,
  AppPlaylistsIdRoute: AppPlaylistsIdRoute,
  AppAlbumsIndexRoute: AppAlbumsIndexRoute,
  AppArtistsIndexRoute: AppArtistsIndexRoute,
  AppGenresIndexRoute: AppGenresIndexRoute,
  AppPlaylistsIndexRoute: AppPlaylistsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
